# =========================
# APPLICATION NAME
# =========================
spring.application.name=TaskEvaluationSys


# DATABASE CONFIGURATION

spring.datasource.url=jdbc:postgresql://localhost:5432/taskAssignmentsDB
spring.datasource.username=postgres
spring.datasource.password=0697


# JPA / HIBERNATE

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SERVER CONFIG
# =========================
server.port=8081
server.servlet.session.timeout=20m

# =========================
# THYMELEAF CONFIG
# =========================
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# =========================
# JWT CONFIGURATION
# =========================
jwt.secret=k9F2vR8mX1qL7zP4sD6nT0bY5cH3jW9aE8uG1xM6pQ2rS7dV5
jwt.expiration=86400000

# =========================
# EMAIL CONFIGURATION (GMAIL SMTP SSL)
# =========================
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nanagyachie@gmail.com
spring.mail.password=bigxccawhzfubaxy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.debug=true

# Admin user configuration (optional - these are the defaults)
app.admin.staff-code=1399459
app.admin.password=admin123
app.admin.email=admin@system.com

# Enable/disable auto initialization (default: true)
app.data.initialization.enabled=true